### ISSUE TITLE
[mac-chrome-1920-내포트폴리오] 매도하기 버튼 없음

### ISSUE THREAD

**Issue by Yeonsu00-12** [100-hours-a-week/5-team-cracre-heartfolio-fe#164]
내용 형식
## 보유 종목

- 매도/매수할 수 있는 버튼이 없음
- 일일이 들어가서 매도해야함..

## 재현하는 방법

동작을 재현하는 단계: 모의투자 페이지 접근 -> 매수/매도 하고 싶은 종목 선택 -> 매수 후 내 포트폴리오 접근 -> 보유종목

## 예상한 동작

- 보유 종목에서 추가매수를 하거나 매도를 할 수 있다.

## 데스크톱(다음 정보를 작성해 주세요):

- Browser : chrome

**Comment by ji006** [comment]
종목 매수/매도 페이지로 이동 가능하게 반영완료

**Comment by ji006** [comment]
develop
