### ISSUE TITLE
[mac-chrome-1920-종목 상세 조회] 관심종목 지정 버튼 빠르게 클릭시 요청이 일부 실패하는 이슈

### ISSUE THREAD

**Issue by Lcrescent3es** [100-hours-a-week/5-team-cracre-heartfolio-fe#172]
내용 형식
##  버그 설명

관심종목 지정/해제 연타시 요청이 일부 실패합니다

## 재현하는 방법

동작을 재현하는 단계:

1. Go to heartfolio.site/stock/18
2. 관심종목 지정 빠르게 클릭
3. See error

## 스크린샷 (옵션)

<img width="1377" alt="image" src="https://github.com/user-attachments/assets/ce19d758-c27d-48bb-901a-c44c015fa736">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 스마트폰(다음 정보를 입력하세요):

- Device: [예) iPhone6]
- OS: [예) iOS8.1]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

프론트 측에서 초당 요청횟수를 제한하면 될 것 같습니다 (저도 준원한테 들은거라 잘 모르겠어요)

**Comment by ji006** [comment]
클릭한 후 요청 가고 받을 때까지 클릭 막아둠

**Comment by ji006** [comment]
develop에 반영 완료
